### ISSUE TITLE
Connect-AzAccount works with PSCredential

### ISSUE THREAD

**Issue by pemo11** [MicrosoftDocs/azure-docs-powershell#920] opened 2019-01-16 19:23 UTC
With az version 1.1 Connect-AzAccount should work with a PSCredential object when using Windows PowerShell 5.1. But Connect-AzAccount still needs a TenantId and the ServicePrincipal parameter. How can I achieve the same kind of login like with Connect-AzureRmAccount?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7cb252-3003-c4b7-02c9-a6600126e6bf
* Version Independent ID: 1068f896-b7a8-de23-ebe6-c03aad0398c9
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azps-1.0.0)
* Content Source: [docs-conceptual/azps-1.0.0/overview.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azps-1.0.0/overview.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2019-01-22 19:43
This looks like a duplicate of #910. The Az module is currently missing support for user/pass logins of this type, an issue which will be addressed in an upcoming release. See https://github.com/Azure/azure-powershell/issues/7430.

**Closed by sptramer** 2019-01-22 19:43 UTC
