### ISSUE TITLE
AZ Install-Module Error Message is Confusing

### ISSUE THREAD

**Issue by nabsul** [MicrosoftDocs/azure-docs-powershell#1760] opened 2021-04-09 16:58 UTC
So many questions about this error message:

![image](https://user-images.githubusercontent.com/11143071/114215003-ec24d100-9919-11eb-9d20-96d857ff7278.png)

- It says I need to run as administrator, but I'm already doing so
- It suggests using `-Scope CurrentUser` and I'm already doing so

So what is the cause of this error?

**Comment by BhargaviAnnadevara-MSFT** [comment] 2021-04-10 05:39
@nabsul Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by nabsul** [comment] 2021-04-10 13:11
For reference, I used the MSI installer and that worked fine.

**Comment by BhargaviAnnadevara-MSFT** [comment] 2021-04-13 17:30
@nabsul Thanks for the info. I tried a couple ways but could not reproduce this issue at my end. The exact command:
```
Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
```
seems to be working as expected with PS `7.1.3` on my machine. Do you, by any chance, have the AzureRM module installed on this machine already?

**Comment by nabsul** [comment] 2021-04-14 17:48
Hi @BhargaviAnnadevara-MSFT . There's a very good chance AzureRM was already installed on the machine. If this is expected behavior, feel free to close this issue. Although I would recommend making the error message clearer in such situations.

Thanks.

**Comment by BhargaviAnnadevara-MSFT** [comment] 2021-04-14 21:19
@nabsul Thanks for the feedback. You might run into some compatibility issues when both modules are installed on the machine so it is recommended that you have just the Az PowerShell module for interacting with Azure.

Also, on a side note, I'd like to let you know that this channel (the [Azure PowerShell Docs](https://github.com/MicrosoftDocs/azure-docs-powershell) repository) is only for driving improvements related to documentation on the [Azure PowerShell module](https://docs.microsoft.com/en-us/powershell/azure).

If you find this cmdlet to not be functioning as expected, please file an issue with the [Azure PowerShell](https://github.com/Azure/azure-powershell/issues) repository so our Engineering Team can also take a look. To provide feedback from the command line itself, use the [Send-Feedback](https://docs.microsoft.com/en-us/powershell/module/az.accounts/send-feedback) cmdlet.

We will now proceed to close this thread, but if there are any further questions regarding the Azure PowerShell documentation, please tag me in your reply and we will be happy to continue the conversation.

**Closed by BhargaviAnnadevara-MSFT** 2021-04-14 21:19 UTC
Labels: Pri3, azure-powershell/svc, cxp, product-question, triaged
