### ISSUE TITLE
"Create" and "Delete" are not valid Azure Powershell verbs

### ISSUE THREAD

**Issue by srcard** [MicrosoftDocs/azure-docs-powershell#1124] opened 2019-06-21 12:53 UTC
Quote: "The verb describes the action (examples include Create, Get, Set, Delete)"
"Create" and "Delete" are not valid Azure Powershell verbs.  The applicable example verbs are likely to be "New" and "Remove"... although "New" isn't a verb in the English language, making it a slightly confusing example choice. The list of valid verbs is linked in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd3c996-55c2-59cc-7be0-cedc187774cd
* Version Independent ID: cc8aa9be-2707-4ef6-e4d9-35498b837289
* Content: [Get started with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/get-started-azureps?view=azps-2.3.2#feedback)
* Content Source: [docs-conceptual/azps-2.3.2/get-started-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.3.2/get-started-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2019-06-21 16:16
The AzureRM module (and now Az module) do use some non-standard verbs. This is by design, to make the intent of the operation clearer regarding resource allocation/deletion. If you'd like to see aliases using the standard verbs made available, please [file an engineering ticket](https://github.com/azure/azure-powershell/issues).

**Comment by srcard** [comment] 2019-06-21 18:18
It sounds like there's a misunderstanding.  I was confused why the quote mentioned Create and Delete.

**Comment by sptramer** [comment] 2019-06-21 19:48
Because these are verbs used frequently in the Azure PowerShell cmdlet set, and so being aware of them is useful for the purposes of searching for cmdlets.

**Comment by sptramer** [comment] 2019-06-24 23:14
Sorry, after I took some time to review this, information in the quote is actually a typo: They should read `New` and `Remove`. This should be fixed within the next couple of days.

**Closed** 2019-06-25 00:28 UTC
Labels: doc-bug, triaged
