### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by TheOnlyWei** [MicrosoftDocs/azure-docs-powershell#1424] opened 2020-06-10 20:49 UTC
Documentation needs to be updated. Right now the different versions of the Azure Stack module all have the same or similar messages.

There is also a suggestion for a common errors section as well because sometimes the error messages from ARM are not user-friendly. E.g., this error:

![8b7f30bf-c312-4fdd-841d-ccad993174a4](https://user-images.githubusercontent.com/19400755/84317099-169ed580-ab21-11ea-8551-aa9197d5211b.jpg)

This error is caused by not being in the "Default Provider Subscription", which obviously the user would not able to know is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d333b76a-571a-f8f5-4875-45f5d030a4b5
* Version Independent ID: 9c031556-607a-b2cf-a24b-dbe040f819b8
* Content: [Azs.AzureBridge.Admin](https://docs.microsoft.com/en-us/powershell/module/azs.azurebridge.admin/?view=azurestackps-2.0.0)
* Content Source: [azurestackps-2.0.0/Azs.AzureBridge.Admin/Azs.AzureBridge.Admin.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azurestackps-2.0.0/Azs.AzureBridge.Admin/Azs.AzureBridge.Admin.md)
* Service: **azure-powershell**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by kobulloc-MSFT** [comment] 2020-06-10 23:40
@TheOnlyWei Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment] 2020-06-14 01:06
@TheOnlyWei It sounds like there are some opportunities to improve our error message (and better error messages lead to a better user experience and easier troubleshooting).  I'm going to include the document author in this (@jeffgilb ) but for product feedback the best channel is feedback.azure.com:
https://feedback.azure.com/forums/344565-azure-stack

I'm happy to submit this feedback on your behalf (or you can submit it yourself if you want to receive notifications, vote, or monitor progress more closely).  I would like a bit more clarification on the first point, where you say that different versions of the Azure Stack module have either the same or similar messages.  Can you provide an example?

**Comment by kobulloc-MSFT** [comment] 2020-06-16 17:03
@TheOnlyWei I've posted your feedback here:

https://feedback.azure.com/forums/344565-azure-stack/suggestions/40680550-default-provider-subscription

Get-AzsAzureBridgeActivation returns "The resource namespace 'Microsoft.AzureBridge.Admin' is invalid.", which in this case is caused by not being in the "Default Provider Subscription" however this is not made clear to the user.

Please feel free to vote and track this issue.  I'm going to close this GitHub issue, but feel free to tag me in your reply if you would like to continue the conversation.

**Closed by kobulloc-MSFT** 2020-06-16 17:03 UTC
Labels: Pri2, azure-powershell/svc, cxp, doc-enhancement, in-progress, triaged
