### ISSUE TITLE
PowerShell does not work for Switch Activity in the Pipeline Data Factory V2 (Set-AzDataFactoryV2Pipeline)

### ISSUE THREAD

**Issue by rezasoltanirezvandeh** [MicrosoftDocs/azure-docs-powershell#1238] opened 2019-10-19 07:27 UTC
Set-AzDataFactoryV2Pipeline  creates Data Factory Pipelines yet if there is a Switch Activity, the Pipeline would not be the same as you expected. 

After Executing the command successfully, I could see the blank Pipeline yet the source code was different from my original Json file, seems it does not like the Switch activity tags and it got replaced with wrong tags by eliminating the typeProperties and replacing the "type": "Switch" to "type": "activity" ! the rest of the properties like the case section was gone too.

**Comment by VikasPullagura-MSFT** [comment] 2019-10-21 06:44
@rezasoltanirezvandeh Thank you for reaching out to us. Can you please provide a link to the document which you are following so that we can engage the correct team to help you.

**Comment by rezasoltanirezvandeh** [comment] 2019-10-21 06:54
Hi Vikas,

I am following the example from the link below:

https://docs.microsoft.com/en-us/azure/data-factory/control-flow-switch-activity

I have checked with simpler pipeline but got the same result.

**Comment by VikasPullagura-MSFT** [comment] 2019-10-21 08:33
@rezasoltanirezvandeh Thanks for getting back with the document details.

Requesting you to open the issue directly on the document as feedback, so that the issue is looked and addressed by the right team.

I am closing this issue now.

**Closed by VikasPullagura-MSFT** 2019-10-21 08:33 UTC
Labels: Pri3, needs-more-info
