### ISSUE TITLE
the Connect-AzAccount cmdlet is still unrecognized even after having installed the module

### ISSUE THREAD

**Issue by UnknownDarkMatter** [MicrosoftDocs/azure-docs-powershell#2108] opened 2022-05-02 13:15 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a78325c3-18f8-b7fc-6fd1-35cf2fd0068e
* Version Independent ID: c6b88fad-dfa9-e0b4-b3ed-7b889c32d813
* Content: [Install the Azure Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-7.5.0)
* Content Source: [docs-conceptual/azps-7.5.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-7.5.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by UnknownDarkMatter** [comment] 2022-05-02 15:49
I found why, it is because I had the Microsoft Azure CLI installed and it caused an Exception during the installation of the AZ Module

**Comment by Karishma-Tiwari-MSFT** [comment] 2022-05-02 17:21
Looks like your issue is resolved. We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.

**Closed by Karishma-Tiwari-MSFT** 2022-05-02 17:21 UTC
Labels: triaged, resolved-by-customer, azure-powershell/svc, Pri1, cxp

**Comment by mikefrobbins** [comment] 2022-05-02 17:53
@UnknownDarkMatter I haven't seen the Azure CLI cause an issue. This problem is normally caused by having both the AzureRM and Az PowerShell modules installed. For more information, see [Command found but could not be loaded](https://docs.microsoft.com/powershell/azure/troubleshooting#command-found-but-could-not-be-loaded).
