### ISSUE TITLE
Command to install Az Module does not work

### ISSUE THREAD

**Issue by SimonDoy** [MicrosoftDocs/azure-docs-powershell#1592] opened 2020-10-08 10:11 UTC
This was found when working with a customer.
The command used to install the module states the following:
Install-Module -Name Az -AllowClobber -Scope CurrentUser

However, this does not seem to work and does not install the Az set of modules.
The cmdlet returns but does not install any modules.

On further investigation, the github repo states (https://github.com/Azure/azure-powershell/releases) using: 
Install-Module -Name Az -Repository PSGallery -Force

This works beautifully.
It seems that the commands need to be updated to include -Repository PSGallery

This was run from a Windows 10 machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b5227da-38b4-acc0-d7e2-8dc90cf60822
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-4.7.0)
* Content Source: [docs-conceptual/azps-4.7.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.7.0/install-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment] 2020-10-08 10:21
@SimonDoy Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment] 2020-10-12 16:46
> Install-Module -Name Az -AllowClobber -Scope CurrentUser
> However, this does not seem to work and does not install the Az set of modules.
> The cmdlet returns but does not install any modules.

@SimonDoy Could you please elaborate the errors you saw upon following this approach, if any? Please provide us with more details so we can analyze further.

It is known that using PSGallery for the first time would [prompt one to set it as a trusted repository](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-4.7.0#install-the-azure-powershell-module). This is because it isn't configured as a trusted repository for PowerShellGet by default.

Also, the `-Repository` parameter need not be passed unless you have added [additional repositories to PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-4.7.0#use-multiple-repositories-with-powershellget) on your system and the `Az` module can be found in more than one of them.

**Comment by BhargaviAnnadevara-MSFT** [comment] 2020-10-14 07:35
@SimonDoy Hope the above inputs help. Are there any further questions here?

**Comment by SimonDoy** [comment] 2020-10-14 08:29
@BhargaviAnnadevara-MSFT Unfortunately there were no errors from the customers machine the command completed but none of the modules were installed. I was expecting to get at least the prompt to trust the repo but that didnt happen. However when we used the command
Install-Module -Name Az -Repository PSGallery -Force
This did cause the trust prompt to appear.
I wonder if the customer has additional repositories and that is why we saw the issue. I will speak with the customer and see if that is the case.

**Comment by BhargaviAnnadevara-MSFT** [comment] 2020-10-14 17:37
@SimonDoy Sure, thanks for the response.
It would be helpful if you can run the cmdlet in Debug mode:
```
Install-Module -Name Az -AllowClobber -Scope CurrentUser -Debug
```
and capture the logs for our perusal. Also check what `Get-PSRepository` cmdlet returns, and let us know what you see. Thanks!

**Comment by BhargaviAnnadevara-MSFT** [comment] 2020-10-16 06:14
@SimonDoy Were you able to gather the requested information?

**Comment by SimonDoy** [comment] 2020-10-16 13:44
@BhargaviAnnadevara-MSFT - Unfortunately not speaking with the customer on Monday, will try again then.

**Comment by BhargaviAnnadevara-MSFT** [comment] 2020-10-20 07:33
@SimonDoy Sure, please let us know once you have an update.

**Comment by mikefrobbins** [comment] 2020-10-26 13:48
@SimonDoy The customer is experiencing this behavior because they are in a non-default configuration. There is a section later in the referenced documentation about how to [Use multiple repositories with PowerShellGet](https://docs.microsoft.com/powershell/azure/install-az-ps#use-multiple-repositories-with-powershellget).

**Comment by BhargaviAnnadevara-MSFT** [comment] 2020-10-29 14:25
@SimonDoy Do you have any further insights to share?

**Comment by SimonDoy** [comment] 2020-10-29 18:44
@BhargaviAnnadevara-MSFT @mikefrobbins 
Thanks for the information, I am on holiday this week and have  not had a chance to speak with the customer. However, if this is the expected behavior with multiple repos ok. I guess the problem is that there is no feedback to say that the installation did not take place.

**Comment by BhargaviAnnadevara-MSFT** [comment] 2020-10-30 06:43
@SimonDoy Thanks for the response, that's totally alright!

If you find this cmdlet to not be functioning as expected, please file an issue with the [Azure PowerShell](https://github.com/Azure/azure-powershell/issues) repository so our Engineering Team can also take a look. To provide feedback from the command line itself, use the [Send-Feedback](https://docs.microsoft.com/en-us/powershell/module/az.accounts/send-feedback) cmdlet.

Since it appears that there are no edits or updates needed to the document in question at this point, I suppose we can close this issue for now. But if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Closed by BhargaviAnnadevara-MSFT** 2020-10-30 06:43 UTC
Labels: Pri2, azure-powershell/svc, cxp, product-question, triaged

**Comment by rcastoro** [comment] 2021-12-01 12:05
Fix for me was un-install the azure powershell module that was installed as a result of the Visual Studios Installer, then manually install the Az Module.

**Comment by mikefrobbins** [comment] 2021-12-01 13:07
@rcastoro Correct. We have that scenario documented in [the troubleshooting section of the installation documentation](https://docs.microsoft.com/powershell/azure/install-az-ps#troubleshooting).

Technical details:

The problem is that Visual Studio installs AzureRM in the all-users scope of Windows PowerShell. The Az module and the AzureRM module are mutually exclusive and cannot be installed in the same PowerShell environment on the same system.

The AzureRM module that's installed for Windows PowerShell by Visual Studio also shows up in PowerShell 7.x. This is due to the $env:PSModulePath for PowerShell 7.x including the all-users paths for Windows PowerShell. If you have a need to install both AzureRM and the Az module, install AzureRM in the current-users scope of Windows PowerShell and the Az module in the current-users scope of PowerShell 7.x.
