### ISSUE TITLE
can't login u/p with connect-azaccount

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/azure-docs-powershell#910] opened 2019-01-10 13:06 UTC
Hey there, I tried different things to log into azureRM with the new Az Module, using Connect-AzAccount. Is it a bug or feature? ;)
Please assist:

`PS C:\> $cred = Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
PS C:\> Connect-AzAccount -Credential $cred

cmdlet Connect-AzAccount at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ServicePrincipal:

#didn't worked

PS C:\> Connect-AzAccount -Credential $cred -ServicePrincipal

cmdlet Connect-AzAccount at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Tenant:

#didn't worked

PS C:\> Connect-AzAccount -Credential $cred -ServicePrincipal -Tenant TENANTID
WARNING: The provided service principal secret will be included in the 'AzureRmContext.json' file found in the user
profile. Please ensure that this directory has appropriate protections.
Connect-AzAccount : AADSTS700016: Application with identifier 'USER' was not found in the directory
'TENANTID'. This can happen if the application has not been installed by the administrator
of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong
tenant
Trace ID: 8d88fb3f-be62-4ce1-a110-f798008d2200
Correlation ID: 2f0c1b7f-9ac2-4469-bb52-a44b506765d8
Timestamp: 2019-01-10 13:02:36Z
At line:1 char:1
+ Connect-AzAccount -Credential $cred -ServicePrincipal -Tenant 7b23ea3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], AdalServiceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

#didn't worked

PS C:\> Connect-AzAccount
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXX1234 to authenticate.

#stuck, even after enterin the code on Website`

**Comment by SRE93** [comment] 2019-01-10 14:11
Connect-AzAccount works now ... just took a while because I am a guest of many tenants ;)
But passthrough credentials with -Credentials parameter still not working.

**Comment by sptramer** [comment] 2019-01-10 18:33
Credential passthrough does probably require tenant information, but I'm unsure why it would be requesting a service principal to have been created to log in. Unless you're using an account with 2FA enabled on it, in which case credentials may cause problems.

It sounds like you may be experiencing a bug with `-Credentials`, so file an issue with engineering at https://github.com/azure/azure-powershell/issues

**Comment by SRE93** [comment] 2019-01-10 18:39
https://github.com/Azure/azure-powershell/issues/8279

**Comment by sptramer** [comment] 2019-01-22 19:39
See also: https://github.com/Azure/azure-powershell/issues/7430 - work is being tracked here to add this support for the 1/22 release. Once that is out, will test the user/pass scenario and see if the issue is resolved. My mistake for having the early release Az module documentation describe a scenario not available in that version of the module.

**Comment by sptramer** [comment] 2019-02-27 23:02
Closed by #980 - it looks like the ability to provide `-Credential` has been removed because of ADAL changes in the .NET Standard auth library. Instead either use interactive login or create a service principal.

**Closed by sptramer** 2019-02-27 23:02 UTC
Labels: doc-bug, product-question, support-request, triaged

**Comment by prabhakarreddy1234** [comment] 2019-07-19 12:17
@sptramer  doesn't service principal login also need `-Credential` ?

**Comment by shravanpragallapati** [comment] 2020-04-19 14:11
Try this once
Connect-AzAccount : User canceled authentication
At line:1 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], AdalServiceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

**Comment by shravanpragallapati** [comment] 2020-04-19 14:12
Try this once

Install-Module -Name Az -AllowClobber -Scope AllUsers
Get-ExecutionPolicy
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine
Connect-AzAccount
