### ISSUE TITLE
PowerShell 7 requires "-Repository PSGallery" to be specified on Install-Module command

### ISSUE THREAD

**Issue by DaveEM** [MicrosoftDocs/azure-docs-powershell#1384] opened 2020-05-13 00:13 UTC
When trying to use the instructions to install the Az module in PowerShell 7, which is PowerShell Core, I got the following error until I specified the -Repository parameter with a value of PSGallery:

PS C:\Users\davmills&gt; Install-Module -Name Az -AllowClobber                                                               WARNING: 'Az' matched module 'Az/1.0.0.7' from provider: 'PowerShellGet', repository 'Cirrus'.                            WARNING: 'Az' matched module 'Az/3.8.0' from provider: 'PowerShellGet', repository 'PSGallery'.                           Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9685                                   Line |                                                                                                                    9685 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters                                                |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to install, multiple modules matched 'Az'. Please specify a single -Repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842f6a18-0b96-0fae-d8f5-d8ae4c565f0e
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-Az-ps?view=azps-3.8.0#feedback)
* Content Source: [docs-conceptual/azps-3.8.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/install-az-ps.md)
* GitHub Login: @dcaro
* Microsoft Alias: **dcaro**

**Comment by MonikaReddy-MSFT** [comment] 2020-05-13 04:24
@DaveEM , Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by mikefrobbins** [comment] 2020-05-14 21:23
Based on the error message, the issue is due to a module named Az being found in more than one repo that's defined on your system. To see the repos defined in PowerShell on your machine, run the `Get-PSRepository` cmdlet.

I will update the referenced doc to account for this since it's an issue that other users could run into if they've defined additional repos on their system in addition to the default PSGallery.

**Comment by MonikaReddy-MSFT** [comment] 2020-05-17 12:46
@mikefrobbins - Thank you for providing more insights and for updating the doc. 

@DaveEM - I hope @mikefrobbins has answered your question. Thanks again for bringing this to our attention.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Closed by MonikaReddy-MSFT** 2020-05-17 12:46 UTC
Labels: Pri1, azure-powershell/svc, cxp, product-question, triaged
