### ISSUE TITLE
Please provide a working script to Uninstall all Az modules and Az module itself

### ISSUE THREAD

**Issue by alvipeo** [MicrosoftDocs/azure-docs-powershell#1772] opened 2021-04-19 12:51 UTC
This - https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-5.8.0#option-2-uninstall-the-az-powershell-module-from-powershellget - is a waste of time. When I needed to re-install Az module because I figured I have FOUR different versions I ended up on this page. So I run the first part of the script and it showed me the modules. But then when you run the second part:
```
$AzModules |
  ForEach-Object {
    Remove-Module -Name $_
    Uninstall-Module -Name $_
  }
```
you get:
> No modules were removed. Verify that the specification of modules to remove is correct and those modules exist in the runspace.

for every single one of them!

Fix this please and make a solid working uninstallation script!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22705105-f9f9-18c3-a184-f40078a4a23f
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-5.8.0)
* Content Source: [docs-conceptual/azps-5.8.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.8.0/uninstall-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by alvipeo** [comment] 2021-04-19 13:39
No matter what I do I still have these versions installed:

```
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.6.1                 Az                                  Core,Desk
Script     3.6.1                 Az                                  Core,Desk
```

Provided script doesn't work.

**Comment by mikefrobbins** [comment] 2021-04-19 15:02
The message "_No modules were removed. Verify that the specification of modules to remove is correct and those modules exist in the runspace._" is returned by the `Remove-Module` cmdlet and is due to the modules not being loaded in memory. We will update the uninstall instructions to account for this. That message doesn't have an impact on the actual uninstall not being performed.

Can you provide us with the output of the following on the system you're experiencing this issue on?

```powershell
Get-Module -Name az -ListAvailable | Select-Object -Property Name, Version, ModuleBase
```

**Comment by alvipeo** [comment] 2021-04-19 18:01
Name Version ModuleBase
---- ------- ----------
Az   4.6.1   [my documents path]\PowerShell\Modules\Az\4.6.1
Az   3.6.1   [my documents path]\PowerShell\Modules\Az\3.6.1

And I have no way uninstalling those.

**Comment by mikefrobbins** [comment] 2021-04-19 19:30
@alvipeo, Can you also provide the output of the following:

```powershell
Get-InstalledModule -Name az.* | Select-Object -Property Name
```

**Comment by alvipeo** [comment] 2021-04-19 20:26
Az.Accounts
Az.Advisor
Az.Aks
Az.AnalysisServices
Az.ApiManagement
Az.ApplicationInsights
Az.Automation
Az.Batch
Az.Billing
Az.Cdn
Az.CognitiveServices
Az.Compute
Az.ContainerInstance
Az.ContainerRegistry
Az.Databricks
Az.DataFactory
Az.DataLakeAnalytics
Az.DataLakeStore
Az.DeploymentManager
Az.DesktopVirtualization
Az.DevTestLabs
Az.Dns
Az.EventGrid
Az.EventHub
Az.FrontDoor
Az.Functions
Az.HDInsight
Az.HealthcareApis
Az.IotHub
Az.KeyVault
Az.Kusto
Az.LogicApp
Az.MachineLearning
Az.ManagedServices
Az.MarketplaceOrdering
Az.Media
Az.Monitor
Az.Network
Az.NotificationHubs
Az.OperationalInsights
Az.PolicyInsights
Az.PowerBIEmbedded
Az.PrivateDns
Az.RecoveryServices
Az.RedisCache
Az.Relay
Az.Resources
Az.ServiceBus
Az.ServiceFabric
Az.SignalR
Az.Sql
Az.Storage
Az.StorageSync
Az.StreamAnalytics
Az.TrafficManager
Az.Websites

**Comment by mikefrobbins** [comment] 2021-04-19 21:26
@alvipeo, It appears that the issue is due to the `Uninstall-Module` cmdlet not including the `AllVersions` parameter.

We've submitted the following update to the referenced article which should be live later today. Here is the update if you'd like to give it a try:

First, you'll need a list of all the Az PowerShell module versions installed on your system.

```azurepowershell-interactive
Get-Module -Name Az -ListAvailable -OutVariable AzVersions
```

You can use the following example to generate a list of all the Az PowerShell modules that need to
be uninstalled in addition to the Az module.

```azurepowershell-interactive
($AzVersions |
  ForEach-Object {
    Import-Clixml -Path (Join-Path -Path $_.ModuleBase -ChildPath PSGetModuleInfo.xml)
  }).Dependencies.Name | Sort-Object -Descending -Unique -OutVariable AzModules
```

Remove the Az modules from memory and then uninstall them.

```azurepowershell-interactive
$AzModules |
  ForEach-Object {
    Remove-Module -Name $_ -ErrorAction SilentlyContinue
    Write-Output "Attempting to uninstall module: $_"
    Uninstall-Module -Name $_ -AllVersions
  }
```

The final step is to remove the Az PowerShell module.

```azurepowershell-interactive
Remove-Module -Name Az -ErrorAction SilentlyContinue
Uninstall-Module -Name Az -AllVersions
```

**Comment by alvipeo** [comment] 2021-04-20 03:45
Guys, this is the problem. I used your script many many times:
```
($AzVersions |
  ForEach-Object {
    Import-Clixml -Path (Join-Path -Path $_.ModuleBase -ChildPath PSGetModuleInfo.xml)
  }).Dependencies.Name | Sort-Object -Descending -Unique -OutVariable AzModules

$AzModules |
  ForEach-Object {
    Remove-Module -Name $_ -ErrorAction SilentlyContinue
    Write-Output "Attempting to uninstall module: $_"
    Uninstall-Module -Name $_ -AllVersions
  }

Remove-Module -Name Az -ErrorAction SilentlyContinue
Uninstall-Module -Name Az -AllVersions
```

and at the end I run this:
```
Get-Module -Name Az -ListAvailable -OutVariable AzVersions
```

and I get... voila!

```
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.6.1                 Az                                  Core,Desk
Script     3.6.1                 Az                                  Core,Desk
```

I can't remove these versions!

**Comment by alvipeo** [comment] 2021-04-20 03:46
It did remove the newer versions though.

**Comment by mikefrobbins** [comment] 2021-04-21 16:15
@alvipeo I've installed the versions you're experiencing issues with and been unable to reproduce the problem. Could you provide the output of the following?

```powershell
Get-InstalledModule -Name Az
```

I'm also going to reach out to our engineering team to see if they can assist.

**Comment by alvipeo** [comment] 2021-04-21 16:56
```
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
4.6.1                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to …
```

**Comment by mikefrobbins** [comment] 2021-04-21 17:02
@alvipeo The response from our engineering team was to perform a manual uninstall since there must be some issue outside the scope of the documentation.

You can simply open your `Documents\PowerShell\Modules` folder and select the Az folder along with all of the Az.* folders and delete them.

![image](https://user-images.githubusercontent.com/6719572/115592727-32bee780-a299-11eb-97ea-a3a8cfde5f90.png)

**Comment by alvipeo** [comment] 2021-04-21 17:09
I assure you that 1) this is __the most effective method__! And 2) __the easiest one__ !

Please keep this method forever and update the docs!

**Comment by mikefrobbins** [comment] 2021-04-26 13:55
@alvipeo Based on your response, it appears the issue you experienced has been resolved and we'll proceed with closing this issue.

**Closed by mikefrobbins** 2021-04-26 13:55 UTC
Labels: Pri1, assigned-to-author, azure-powershell/svc, cxp, doc-enhancement, in-progress, triaged
