### ISSUE TITLE
Get-AZVM output restriction?

### ISSUE THREAD

**Issue by pjamesburwell** [MicrosoftDocs/azure-docs-powershell#2676] opened 2023-08-07 21:03 UTC
[Running Get-AZVM restricts the output to only 100 servers? Where is the switch to overcome this restriction? -Patrick@Burwell.tech]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d02fee70-5faf-15e1-7fb7-4b76e53f91b0
* Version Independent ID: c186d2b8-ecb0-9d47-bb2a-3a3ede3f0c70
* Content: [Query output of Azure PowerShell cmdlets](https://learn.microsoft.com/en-us/powershell/azure/queries-azureps?view=azps-10.2.0)
* Content Source: [docs-conceptual/azps-10.2.0/queries-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.2.0/queries-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by isra-fel** [comment] 2023-08-08 01:47
Hey @pjamesburwell thanks for reporting. Azure PowerShell is open source so next time you could just submit issues here: https://github.com/Azure/azure-powershell/issues/new/choose 😀 

cc @bilaakpan-ms @sandido @haagha @grizzlytheodore

**Comment by YashikaTyagii** [comment] 2023-08-08 04:11
@pjamesburwell 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mikefrobbins** [comment] 2023-08-08 22:19
@pjamesburwell Since this is a documentation repository and the issue isn't a problem with the documentation, we'll proceed with closing your issue. I recommend reporting this issue in the [Azure PowerShell product repository](https://github.com/Azure/azure-powershell/issues) so it can be properly triaged as a possible bug in the Get-AzVM cmdlet.

**Closed by mikefrobbins** 2023-08-08 22:19 UTC
Labels: triaged, assigned-to-author, product-question, azure-powershell/svc, Pri1

**Comment by mikefrobbins** [comment] 2023-08-08 22:32
@pjamesburwell I wanted to elaborate on my previous response. There are no parameters for Get-AzVM that would restrict or increase the results to a specific number of VM's. Based on the issue you reported, it sounds like a bug in the cmdlet. I recommend [updating to the latest version](https://learn.microsoft.com/powershell/azure/install-azure-powershell). If that doesn't correct the problem, please report this as an issue with the product using the link in my previous comment.
