### ISSUE TITLE
Link to "Download PDF" is not working

### ISSUE THREAD

**Issue by StevensLim** [MicrosoftDocs/azure-docs-powershell#1038] opened 2019-04-18 04:25 UTC
Can't download the PDF version of this documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd44e490-bfce-8a78-629b-a8886af52f64
* Version Independent ID: 1068f896-b7a8-de23-ebe6-c03aad0398c9
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azps-1.7.0#feedback)
* Content Source: [docs-conceptual/azps-1.7.0/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.7.0/overview.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2019-04-23 20:04
Duplicate of #1030

**Closed by sptramer** 2019-04-23 20:04 UTC
