### ISSUE TITLE
Property 'NumberOfVirtualNetworkLinks' not reported

### ISSUE THREAD

**Issue by ChrisSommers** [MicrosoftDocs/azure-docs-powershell#1885] opened 2021-09-07 09:42 UTC
Using 1.0.3 of the Az.PrivateDns module, the NumberOfVirtualNetworkLinks property seems to always show 0, even when there are linked VNets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ebeb37a-283d-7500-83d0-51c8c75255df
* Version Independent ID: 110b4b89-cbfc-a095-991e-cb8460786d73
* Content: [Get-AzPrivateDnsZone (Az.PrivateDns)](https://docs.microsoft.com/en-us/powershell/module/az.privatedns/get-azprivatednszone?view=azps-6.3.0)
* Content Source: [src/PrivateDns/PrivateDns/help/Get-AzPrivateDnsZone.md](https://github.com/Azure/azure-powershell/blob/main/src/PrivateDns/PrivateDns/help/Get-AzPrivateDnsZone.md)
* Service: **azure-powershell**
* GitHub Login: @dcaro
* Microsoft Alias: **dcaro**

**Comment by BhargaviAnnadevara-MSFT** [comment] 2021-09-07 10:57
@ChrisSommers Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment] 2021-09-10 17:59
@ChrisSommers Indeed, this is true when you invoke the `Get-AzPrivateDnsZone` cmdlet **without** the `-ResourceGroup` and `-Name` parameter. It seems like this property isn't populated although present in the ouput of `Get-AzPrivateDnsZone`. However, when the `-ResourceGroup` and `-Name` parameters are passed along, you'd see the property reports the correct value.

Digging a little deeper, this is because the `Get-AzPrivateDnsZone` and `Get-AzPrivateDnsZone -ResourceGroupName <RG-name>` commands invoke the [Private Zones - List](https://docs.microsoft.com/en-us/rest/api/dns/privatedns/private-zones/list) and [Private Zones - List By Resource Group](https://docs.microsoft.com/en-us/rest/api/dns/privatedns/private-zones/list-by-resource-group) ​REST APIs under the hood, that has the `NumberOfVirtualNetworkLinks` property set to `0` in the response. Whereas, `Get-AzPrivateDnsZone -ResourceGroupName <RG-name> -Name <Private-Zone-Name>` command calls the [Private Zones - Get](https://docs.microsoft.com/en-us/rest/api/dns/privatedns/private-zones/get) REST API that populates the `NumberOfVirtualNetworkLinks` property as well with the appropriate value.

To work around this behavior, please run the following snippet:
```
$AllPrivateDnsZones = Get-AzPrivateDnsZone
$AllPrivateDnsZonesExtended = @()

foreach($PrivateDnsZone in $AllPrivateDnsZones)
{
    $PrivateDnsZoneExtended = Get-AzPrivateDnsZone -ResourceGroupName $PrivateDnsZone.ResourceGroupName -Name $PrivateDnsZone.Name
    $AllPrivateDnsZonesExtended += $PrivateDnsZoneExtended
}

$AllPrivateDnsZonesExtended | ft -Property Name, ResourceGroupName, NumberOfVirtualNetworkLinks
```

Sample Output:
```
Name                               ResourceGroupName  NumberOfVirtualNetworkLinks
----                               -----------------  ---------------------------
privatelink.blob.core.windows.net  MyResourceGroup1                             1
privatelink.datafactory.azure.net  MyResourceGroup2                             1
```

To confirm whether this is indeed the expected behavior, I'd suggest you to open an issue [here ](https://github.com/Azure/azure-powershell/issues/new/choose) with the [Azure/azure-powershell](https://github.com/Azure/azure-powershell) repo so that our Engineering Team can investigate and clarify. To provide feedback from the command line itself, use the [Send-Feedback](https://docs.microsoft.com/en-us/powershell/module/az.accounts/send-feedback) cmdlet.

Having said that, I'd like to let you know that this channel (the [Azure PowerShell Docs](https://github.com/MicrosoftDocs/azure-docs-powershell) repository) is only for driving improvements related to documentation on the [Azure PowerShell module](https://docs.microsoft.com/en-us/powershell/azure). At this point, it appears that there are no immediate edits or updates needed to the document in question. Hence closing this issue for now. If there are any further questions regarding the Azure PowerShell documentation, please tag me in your reply and we will be happy to continue the conversation.

**Closed by BhargaviAnnadevara-MSFT** 2021-09-10 17:59 UTC
Labels: triaged, product-question, azure-powershell/svc, Pri1, cxp
