### ISSUE TITLE
Differences between 10.4.0 and 10.4.1

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/azure-docs-powershell#2781] opened 2023-10-20 14:33 UTC
Hi

25 days ago you released a version 10.4.0
And then two days later you released version 10.4.1

The release notes speaks about only 10.4.0, so is this 10.4.1 just a bug fix or how it should be handled?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b44c6d3f-9f69-00a1-3ba5-b97306a670b1
* Version Independent ID: 13ab3c45-9746-6b1c-66af-bbb1f8f5de60
* Content: [Azure PowerShell release notes](https://learn.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-10.4.1)
* Content Source: [docs-conceptual/azps-10.4.1/release-notes-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.4.1/release-notes-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment] 2023-10-20 15:12
@Petri-X - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can review and update accordingly.

**Comment by mikefrobbins** [comment] 2023-10-23 13:44
@Petri-X Az version 10.4.1 was released because there was a regression in 10.4.0. I'll add a note to the release notes.

**Closed** 2023-10-24 13:32 UTC
Labels: triaged, issue-doc-idea, issue-docs-experience, azure-powershell/svc, Pri1, cxp
