### ISSUE TITLE
Put the "use Az instead" banner on every page

### ISSUE THREAD

**Issue by TylerLeonhardt** [MicrosoftDocs/azure-docs-powershell#1449] opened 2020-06-25 18:31 UTC
Google, Bing, and other search engines take you right to pages like:

https://docs.microsoft.com/en-us/powershell/module/azurerm.websites/get-azurermappserviceplan?view=azurermps-6.13.0

which don't mention `Az.*` at all. I just had someone try to use this module on Linux and had to explain to them the difference between Az and AzureRM.

Can we get a banner on every AzureRM page to say "use Az" please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab81ac50-5213-1282-d66c-e0c70794d2eb
* Version Independent ID: 86324274-e59e-d272-0554-f51a63e7ec5c
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azurerm/overview?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/overview.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment] 2020-06-25 22:41
@TylerLeonhardt Thank you for the feedback!  We've assigned this to the document author.

**Comment by mikefrobbins** [comment] 2020-07-08 15:45
We are exploring our options for adding a banner. One thing we have to take into consideration is [Azure Stack still requires the AzureRM module](https://docs.microsoft.com/azure-stack/operator/azure-stack-powershell-install) and we don't want to confuse those customers.

**Comment by TylerLeonhardt** [comment] 2020-07-08 16:01
@mikefrobbins are you sure? There's an article right below that one called ["PowerShell Az"](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2002)

**Comment by mikefrobbins** [comment] 2020-07-08 16:07
Our current information about Azure Stack requiring AzureRM was confirmed by @mattbriggs, their docs writer. We have also reached out to their engineering team and are waiting to hear back from them.

**Comment by kilasuit** [comment] 2020-08-06 20:22
@mikefrobbins can we get a banner that clearly mentions that then, ideally one that isn't needed to be added directly to all individual pages so that update/removal can be much easier in future.

**Comment by mikefrobbins** [comment] 2020-08-06 20:39
@kilasuit Already in the works.

**Comment by mikefrobbins** [comment] 2020-08-26 21:01
A banner has been added to all AzureRM reference and conceptual docs. An example of this banner can be viewed in the any of the docs such as [Connect-AzureRmAccount](https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/connect-azurermaccount).

**Comment by TylerLeonhardt** [comment] 2020-08-26 22:15
@mikefrobbins can I suggest a link to the Az module (docs or repo or powershellgallery link) somewhere in that banner? I foresee some random person not using AzureRM or Az stumbling upon an AzureRM cmdlet and wanting to know where to get started with Az. The migration link is really only good if they already used AzureRM.

The dream would be that AzureRM commands point to their Az equivalent but I know that there isn't always equivalency there so that would be challenging.

**Comment by mikefrobbins** [comment] 2020-08-26 22:56
Good point. We actually had [more content](https://github.com/mikefrobbins/azure-docs-powershell/blob/2ca63539f6e4c5767e81328a86d78833f9de7fbb/includes/migrate-to-az-banner.md) in the banner originally, but trimmed it down due to concerns about readers skipping over a large block of text. Let's see if we can find a happy medium.

I also like the idea of having a link to the corresponding Az cmdlet. That will be static content in each doc so I'll provide a link once I add a couple for review. That content won't need to change once added. I'll combine that with an include file that's easily updatable so we can globally change the message once we announce deprecation.

**Comment by dcaro** [comment] 2020-08-26 23:05
@TylerLeonhardt you have a point. We have some additional work planned on this topic in the coming weeks and I hope that we can find something that works for both cases.

**Comment by mikefrobbins** [comment] 2020-09-15 20:28
We have updated the banner for a friendlier new user experience in addition to providing information for users who should migrate from AzureRM. At this point, we have decided not to add direct links to the corresponding Az cmdlets since that is a moving target based on our research.

**Closed by mikefrobbins** 2020-09-15 20:28 UTC
Labels: Pri2, assigned-to-author, awaiting-product-team-response, azure-powershell/svc, doc-enhancement, triaged
